# Generated by Django 5.2 on 2025-08-13 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(default='usuario', max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('huella_template', models.BinaryField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia')], max_length=20, null=True)),
                ('fecha_inicio_plan', models.DateField(blank=True, null=True)),
                ('fecha_fin_plan', models.DateField(blank=True, null=True)),
                ('tipo_publico', models.CharField(choices=[('Normal', 'Normal'), ('Estudiante', 'Estudiante'), ('AdultoMayor', 'Adulto Mayor')], default='Normal', max_length=20)),
                ('sub_plan', models.CharField(blank=True, choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20, null=True)),
                ('accesos_restantes', models.IntegerField(default=0)),
                ('accesos_semana_restantes', models.IntegerField(default=0)),
                ('ultimo_reset_semana', models.DateField(blank=True, null=True)),
                ('precio_asignado', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100, unique=True)),
                ('accesos_por_semana', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_publico', models.CharField(choices=[('Normal', 'Normal'), ('Estudiante', 'Estudiante'), ('Adulto Mayor', 'Adulto Mayor')], max_length=20)),
                ('sub_plan', models.CharField(choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20)),
                ('precio', models.PositiveIntegerField(verbose_name='Precio (CLP)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_inicial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor')], max_length=20)),
                ('duracion', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], default='Mensual', max_length=20)),
                ('sub_plan', models.CharField(choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20)),
            ],
            options={
                'unique_together': {('tipo', 'duracion')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='mensualidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mensualidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plan_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planpersonalizado'),
        ),
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
