# Generated by Django 5.2 on 2025-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='plan_personalizado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='planes_personalizados',
            field=models.ManyToManyField(blank=True, to='core.planpersonalizado'),
        ),
    ]
