# Generated by Django 5.2 on 2025-07-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=10, null=True),
        ),
    ]
