# Generated by Django 5.2 on 2025-08-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_plan_personalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePlanPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesos_semana_restantes', models.IntegerField(default=0)),
                ('ultimo_reset_semana', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_planes_personalizados', to='core.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planpersonalizado')),
            ],
        ),
    ]
