# Generated by Django 5.2 on 2025-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clienteplanpersonalizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientePlanPersonalizado',
        ),
    ]
