# Generated by Django 5.2 on 2025-07-24 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
