# Generated by Django 5.2 on 2025-08-17 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_clienteplanpersonalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plan_personalizado_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_activos', to='core.planpersonalizado'),
        ),
    ]
