# Generated by Django 5.2 on 2025-07-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_fecha_inicio_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='nombreUsuario',
            field=models.CharField(default='usuario', max_length=50),
        ),
    ]
