# Generated by Django 5.2 on 2025-08-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_plan_personalizado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
