# Generated by Django 5.2 on 2025-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_ingresoproducto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_inicial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
