# Generated by Django 5.2 on 2025-08-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precios_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='precio_final',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
