# Generated by Django 5.2 on 2025-08-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_stock_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
