# Generated by Django 5.2 on 2025-08-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_precios_precio_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planpersonalizado',
            old_name='accesos_por_semana',
            new_name='accesos_por_mes',
        ),
    ]
