# Generated by Django 5.2 on 2025-08-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cliente_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
