# Generated by Django 5.2 on 2025-08-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_accesos_por_semana_planpersonalizado_accesos_por_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='accesos_semana_restantes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ultimo_reset_semana',
        ),
    ]
