# Generated by Django 5.2 on 2025-08-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cliente_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_fin_plan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
