# Generated by Django 5.2 on 2025-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cliente_accesos_semana_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='duracion',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual'), ('Semestral', 'Semestral')], default='Mensual', max_length=20),
        ),
    ]
