# Generated by Django 5.2 on 2025-08-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_fecha_fin_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='duracion',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], default='Mensual', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('tipo', 'duracion')},
        ),
    ]
