# Generated by Django 5.2 on 2025-08-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mensualidad_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultimo_reset_semana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
