# Generated by Django 5.2 on 2025-08-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente_ultimo_reset_semana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ultimo_reset_semana',
            new_name='ultimo_reset_mes',
        ),
    ]
