# Generated by Django 5.2 on 2025-08-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mensualidad_duracion_alter_mensualidad_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='huella_template',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
