# Generated by Django 5.2 on 2025-08-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_huella_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accesos_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sub_plan',
            field=models.CharField(blank=True, choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20, null=True),
        ),
    ]
