# Generated by Django 5.2 on 2025-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_ultimo_reset_semana_cliente_ultimo_reset_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(choices=[('subplan', 'Subplan'), ('plan_personalizado', 'Plan Personalizado')], default='subplan', max_length=20),
        ),
    ]
