# Generated by Django 5.2 on 2025-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_asistencia_tipo_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='accesos_restantes',
            field=models.FloatField(default=0),
        ),
    ]
