# Generated by Django 5.2 on 2025-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_accesos_restantes_cliente_sub_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accesos_semana_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_reset_semana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
