# Generated by Django 5.2 on 2025-08-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cliente_accesos_semana_restantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpersonalizado',
            name='accesos_por_semana',
            field=models.IntegerField(default=0),
        ),
    ]
