# Generated by Django 5.2 on 2025-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cliente_accesos_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='extra_titanio',
            field=models.CharField(blank=True, choices=[('ninguno', 'Sin Extra'), ('Adamantium', 'Sesión Nutricional + Kinesiología'), ('Vibranium', 'Nutricional + Kinesiología + Full Accesos')], max_length=20, null=True),
        ),
    ]
