# Generated by Django 5.2 on 2025-08-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cliente_extra_titanio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='extra_titanio',
        ),
    ]
