# Generated by Django 5.2 on 2025-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_planpersonalizado_accesos_por_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_plan',
            field=models.CharField(choices=[('pendiente', 'Pendiente de activación'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
