# Generated by Django 5.2 on 2025-08-24 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_cliente_extra_titanio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('nutricional', 'Asistió Sesión Nutricional'), ('kinesiologia', 'Asistió Sesión Kinesiología')], max_length=20)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.cliente')),
            ],
        ),
    ]
