# Generated by Django 5.2 on 2025-08-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cliente_estado_plan_alter_cliente_fecha_inicio_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado_plan',
        ),
    ]
