# Generated by Django 5.2 on 2025-09-01 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('venta', 'Venta'), ('asistencia', 'Asistencia'), ('renovar', 'Renovación'), ('cambio_plan', 'Cambio de Plan'), ('stock', 'Stock')], max_length=20)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admin')),
            ],
        ),
    ]
