# Generated by Django 5.2 on 2025-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cliente_estado_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_plan',
            field=models.CharField(choices=[('pendiente', 'Pendiente de activación'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido')], default='pendiente', help_text='Estado actual del plan del cliente', max_length=20),
        ),
    ]
