# Generated by Django 5.2 on 2025-09-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historialaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='plan_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planpersonalizado'),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='duracion',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Diario', 'Diario')], default='Mensual', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='sub_plan',
            field=models.CharField(blank=True, choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor'), ('Pase Diario', 'Pase Diario')], max_length=20),
        ),
    ]
