# Generated by Django 5.2 on 2025-08-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cliente_estado_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado_plan',
        ),
    ]
