# Generated by Django 5.2 on 2025-09-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_asistencia_plan_personalizado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
    ]
