# Generated by Django 5.2 on 2025-08-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cliente_estado_plan'),
    ]

    operations = [
   
        migrations.AddField(
            model_name='cliente',
            name='tipo_publico',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Estudiante', 'Estudiante'), ('AdultoMayor', 'Adulto Mayor')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_publico', models.CharField(choices=[('Normal', 'Normal'), ('Estudiante', 'Estudiante'), ('AdultoMayor', 'Adulto Mayor')], max_length=20)),
                ('sub_plan', models.CharField(choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20)),
                ('precio', models.PositiveIntegerField(verbose_name='Precio (CLP)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'db_table': 'precios',
                'unique_together': {('tipo_publico', 'sub_plan')},
            },
        ),
    ]
