# Generated by Django 5.2 on 2025-08-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cliente_precio_asignado_cliente_tipo_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precio_asignado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
