# Generated by Django 5.2 on 2025-09-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor'), ('Pase Diario', 'Pase Diario'), ('Gratis', 'Gratis')], max_length=20),
        ),
    ]
