# Generated by Django 5.2 on 2025-08-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cliente_precio_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='sub_plan',
            field=models.CharField(choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
