# Generated by Django 5.2 on 2025-09-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_mensualidad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
