# Generated by Django 5.2 on 2025-08-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mensualidad_sub_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sub_plan',
        ),
    ]
