# Generated by Django 5.2 on 2025-09-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mensualidad_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='precio',
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor'), ('Pase Diario', 'Pase Diario'), ('Gratis', '')], max_length=20),
        ),
    ]
