# Generated by Django 5.2 on 2025-08-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_cliente_sub_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sub_plan',
            field=models.CharField(blank=True, choices=[('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20, null=True),
        ),
    ]
