# Generated by Django 5.2 on 2025-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_mensualidad_precio_alter_mensualidad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor'), ('Pase Diario', 'Pase Diario'), ('Gratis', 'Gratis')], max_length=20),
        ),
    ]
