# Generated by Django 5.2 on 2025-08-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cliente_sub_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precios',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='precios',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='precios',
            table=None,
        ),
    ]
