# Generated by Django 5.2 on 2025-09-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_mensualidad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=20),
            preserve_default=False,
        ),
    ]
