# Generated by Django 5.2 on 2025-08-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_precios_options_alter_precios_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='tipo_publico',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Estudiante', 'Estudiante'), ('Adulto Mayor', 'Adulto Mayor')], max_length=20),
        ),
    ]
