# Generated by Django 5.2 on 2025-09-07 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoproducto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
