# Generated by Django 5.2 on 2025-09-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ingresoproducto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoproducto',
            name='fecha',
        ),
    ]
