# Generated by Django 5.2 on 2025-10-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='sub_plan',
            field=models.CharField(choices=[('Pase Diario', 'Pase Diario'), ('Bronce', 'Bronce (4 Accesos)'), ('Hierro', 'Hierro (8 Accesos)'), ('Acero', 'Acero (12 Accesos)'), ('Titanio', 'Titanio (Acceso Libre)')], max_length=20),
        ),
    ]
