# Generated by Django 5.2.5 on 2025-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_precios_sub_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('tipo_atencion', models.CharField(choices=[('Kinesiología', 'Kinesiología'), ('Nutrición', 'Nutrición'), ('Ambos', 'Ambos')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NombresProfesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('profesion', models.CharField(choices=[('Kinesiologo', 'Kinesiologo'), ('Nutricionista', 'Nutricionista')], max_length=20)),
            ],
        ),
    ]
