# Generated by Django 5.2.5 on 2025-10-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_clienteexterno_nombresprofesionales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nombresprofesionales',
            name='rut',
        ),
    ]
