# Generated by Django 5.2.5 on 2025-10-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_nombresprofesionales_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='core.nombresprofesionales'),
        ),
    ]
