# Generated by Django 5.2.5 on 2025-10-09 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sesion_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='cliente_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_externas', to='core.clienteexterno'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
