# Generated by Django 5.2.5 on 2025-10-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_sesion_cliente_externo_alter_sesion_cliente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='tipo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Normal', 'Normal'), ('Adulto Mayor', 'Adulto Mayor'), ('Pase Diario', 'Pase Diario'), ('Gratis', 'Gratis'), ('Plan AM Estudiante', 'Plan AM (Estudiante)'), ('Plan AM Normal', 'Plan AM (Normal)'), ('Plan AM Adulto Mayor', 'Plan AM (Adulto Mayor)')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('tipo', 'duracion', 'sub_plan')},
        ),
    ]
