# Generated by Django 5.2.5 on 2025-10-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_mensualidad_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('tipo', 'duracion')},
        ),
    ]
