# Generated by Django 5.2.5 on 2025-10-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_mensualidad_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('tipo', 'duracion', 'sub_plan')},
        ),
    ]
