# Generated by Django 5.2.5 on 2025-10-16 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_mensualidad_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='huella_template',
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('tipo', 'duracion')},
        ),
        migrations.CreateModel(
            name='AgendaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(choices=[('Box 1', 'Box 1 - Kinesiología'), ('Box 2', 'Box 2 - Nutrición')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('cliente_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clienteexterno')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='core.nombresprofesionales')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('box', 'fecha', 'hora_inicio')},
            },
        ),
    ]
