# Generated by Django 5.2.5 on 2025-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_cliente_huella_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profesion',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Kinesiologo', 'Kinesiólogo'), ('Nutricionista', 'Nutricionista')], default='Administrador', max_length=20),
        ),
    ]
