# Generated by Django 5.2.5 on 2025-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_admin_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accesos_personalizados_restantes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='accesos_subplan_restantes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profesion',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Kinesiologo', 'Kinesiologo'), ('Nutricionista', 'Nutricionista')], default='Administrador', max_length=20),
        ),
    ]
