# Generated by Django 5.2.5 on 2025-11-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cliente_accesos_personalizados_restantes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendaprofesional',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='coach_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to='core.nombresprofesionales'),
        ),
        migrations.AddField(
            model_name='planpersonalizado',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_asignados', to='core.nombresprofesionales'),
        ),
        migrations.AlterField(
            model_name='nombresprofesionales',
            name='profesion',
            field=models.CharField(choices=[('Kinesiologo', 'Kinesiologo'), ('Nutricionista', 'Nutricionista'), ('Coach', 'Coach')], max_length=20),
        ),
    ]
