# Generated by Django 5.2 on 2025-11-11 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_agendaprofesional_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admin'),
        ),
        migrations.AlterField(
            model_name='clienteexterno',
            name='tipo_atencion',
            field=models.CharField(choices=[('Kinesiología', 'Kinesiología'), ('Nutrición', 'Nutrición'), ('Masajista', 'Masajista'), ('Ambos', 'Ambos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nombresprofesionales',
            name='profesion',
            field=models.CharField(choices=[('Kinesiologo', 'Kinesiologo'), ('Nutricionista', 'Nutricionista'), ('Coach', 'Coach'), ('Masajista', 'Masajista')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='tipo_sesion',
            field=models.CharField(choices=[('nutricional', 'Asistió Sesión Nutricional'), ('kinesiologia', 'Asistió Sesión Kinesiología'), ('masajista', 'Asistió Sesión Masajista')], max_length=20),
        ),
    ]
