# Generated by Django 5.2.5 on 2025-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_cliente_coach_asignado_planpersonalizado_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombresprofesionales',
            name='profesion',
            field=models.CharField(choices=[('Kinesiologo', 'Kinesiologo'), ('Nutricionista', 'Nutricionista'), ('Coach', 'Coach')], max_length=20),
        ),
    ]
