# Generated by Django 5.2.5 on 2026-01-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_venta_admin_alter_clienteexterno_tipo_atencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('2x1', 'Promo 2x1')], default='2x1', max_length=10)),
                ('precio_total', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.grupoplan'),
        ),
    ]
