# Generated by Django 5.2.5 on 2026-01-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_grupoplan_cliente_grupo_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoplan',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='grupoplan',
            name='precio_total',
        ),
    ]
